export const CHANGE_AUTH = 'CHANGE_AUTH';
export const GET_USER_LOCATIONID = 'GET_USER_LOCATIONID';
export const SET_USER_LOCATIONID = 'SET_USER_LOCATIONID';
export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const REM_PRODUCT_BASKET = 'REM_PRODUCT_BASKET';
export const EMPTY_BASKET = 'EMPTY_BASKET';